import type { Topic } from '../types';
import { REVIEWED_ON, clarevo, planalto } from './common';

/**
 * Dúvidas frequentes (spec3 §3.4): perguntas sobre privacidade e uso do app, sem subtítulo, com fontes do projeto.
 * `voltei-depois` foi reescrito para A3 e A4 e não conta dias sem anotar.
 */
export const DUVIDAS_TOPICS: Topic[] = [
  {
    slug: 'quem-ve-meus-dados',
    section: 'duvidas',
    kind: 'pergunta',
    status: 'publicado',
    title: 'Quem vê meus dados?',
    subtitle: null,
    question: null,
    short: 'No Pessoal, só você. As permissões são conferidas no servidor a cada leitura, não só escondidas na tela.',
    paragraphs: [
      'Cada registro pertence a um espaço, Pessoal ou Família. No Pessoal, só você vê, anota, edita e exclui.',
      'Quando houver convites para a Família, cada pessoa terá permissões próprias, e entrar numa família não mostra seu histórico pessoal.',
    ],
    example: null,
    calculation: null,
    hypotheses: null,
    facts: [],
    keywords: ['privacidade', 'permissões', 'família', 'pessoal', 'segurança'],
    related: ['empresa-ve', 'apagar-dados'],
    sources: [clarevo('D-006', 'D-012')],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: null,
  },
  {
    slug: 'empresa-ve',
    section: 'duvidas',
    kind: 'pergunta',
    status: 'publicado',
    title: 'A empresa que oferece o benefício vê meus gastos?',
    subtitle: null,
    question: null,
    short: 'Não. A empresa administra seu acesso ao plano e não vê seus registros financeiros, nem em números somados aos de outras pessoas.',
    paragraphs: [
      'Recebimentos, gastos, contas a pagar e gastos fixos ficam no seu espaço pessoal. O banco de dados nega a leitura a quem administra o benefício, e isso é testado.',
    ],
    example: null,
    calculation: null,
    hypotheses: null,
    facts: [],
    keywords: ['empregador', 'benefício', 'privacidade', 'rh'],
    related: ['quem-ve-meus-dados'],
    sources: [clarevo('D-006')],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: null,
  },
  {
    slug: 'demonstracao',
    section: 'duvidas',
    kind: 'pergunta',
    status: 'publicado',
    title: 'O que é a demonstração?',
    subtitle: null,
    question: null,
    short: 'Um modo para conhecer o app, com acesso simulado e dados fictícios, marcado com o selo Demonstração. Uma conta nova nunca recebe esses dados.',
    paragraphs: [
      'Na demonstração, registros e valores são inventados e ficam só neste aparelho enquanto o app está aberto. Ao criar sua conta, você começa sem nenhum registro.',
    ],
    example: null,
    calculation: null,
    hypotheses: null,
    facts: [],
    keywords: ['dados de exemplo', 'teste', 'conta nova'],
    related: ['quem-ve-meus-dados'],
    sources: [clarevo('D-013', 'D-016')],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: null,
  },
  {
    slug: 'marcar-como-paga',
    section: 'duvidas',
    kind: 'pergunta',
    status: 'publicado',
    title: 'Como marcar uma conta como paga?',
    subtitle: null,
    question: null,
    short: 'Abra a conta em Contas a pagar e toque em Marcar como paga. Informe o valor e a data em que pagou: o Clarevo cria um único gasto em Pago.',
    paragraphs: [
      'O valor pago pode ser diferente do previsto, por multa ou desconto. A conta fica quitada e o gasto entra em Pago no mês da data do pagamento.',
      'Errou? Abra a conta e toque em Desfazer pagamento: o gasto sai de Pago e a conta volta para Ainda a pagar.',
      'Várias contas vencidas? Use Revisar vencidas.',
    ],
    example: null,
    calculation: null,
    hypotheses: null,
    facts: [],
    keywords: ['pagar conta', 'paguei', 'desfazer pagamento', 'quitada', 'contas a pagar'],
    related: ['contei-duas-vezes', 'multa-juros-atraso', 'realizado-previsto'],
    sources: [clarevo('D-021')],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: null,
  },
  {
    slug: 'contei-duas-vezes',
    section: 'duvidas',
    kind: 'pergunta',
    status: 'publicado',
    title: 'Anotei duas vezes. Como corrigir?',
    subtitle: null,
    question: null,
    short:
      'Se você anotou um gasto e também marcou a conta a pagar como paga, o valor entrou duas vezes em Pago. Exclua o gasto anotado à parte e mantenha o da conta.',
    paragraphs: [
      'O gasto criado pela conta paga mostra Origem: Conta a pagar. O outro pode ser excluído no detalhe dele, em Excluir registro.',
      'Se você anotou o pagamento como gasto e a conta ficou em aberto, exclua a conta a pagar (num gasto fixo, só a conta daquele mês).',
      'Com cartão, anote as compras ou a fatura, nunca as duas.',
    ],
    example: null,
    calculation: null,
    hypotheses: null,
    facts: [],
    keywords: ['duplicado', 'repetido', 'excluir registro', 'corrigir'],
    related: ['fatura', 'marcar-como-paga', 'gasto-fixo'],
    sources: [clarevo('D-021', 'D-024')],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: null,
  },
  {
    slug: 'voltei-depois',
    section: 'duvidas',
    kind: 'pergunta',
    status: 'publicado',
    title: 'Fiquei um tempo sem abrir o app. O que acontece?',
    subtitle: null,
    question: null,
    short:
      'O Clarevo não cria contas antigas sozinho. Depois de um tempo sem anotar, o Resumo mostra a faixa Seus últimos meses, e você decide se atualiza ou segue adiante.',
    paragraphs: [
      'Gastos fixos e parcelamentos criam as contas do mês anterior ao seguinte, e contas do ano entram dois meses antes do primeiro vencimento. Meses mais antigos aparecem no detalhe como sem conta registrada.',
      'Na revisão dos últimos meses, você marca o que já pagou e o que não houve, e anota recebimentos e gastos de cada mês, se quiser. Seguir adiante não cria nem apaga nada.',
      'Contas vencidas também aparecem em Revisar vencidas, em Contas a pagar.',
    ],
    example: null,
    calculation: null,
    hypotheses: null,
    facts: [],
    keywords: ['voltar', 'meses sem anotar', 'seus últimos meses', 'atualizar', 'seguir adiante'],
    related: ['sem-registro', 'marcar-como-paga'],
    sources: [clarevo('D-024', 'D-029', 'D-030')],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: null,
  },
  {
    slug: 'apagar-dados',
    section: 'duvidas',
    kind: 'pergunta',
    status: 'rascunho',
    title: 'Como apagar meus dados?',
    subtitle: null,
    question: null,
    short:
      'Você pode excluir cada registro e cada conta a pagar no detalhe deles. Para excluir a conta inteira e todos os dados, escreva para {canal de P-023}.',
    paragraphs: [
      'Excluir tira o item das listas e dos totais. Fica um rastro técnico mínimo de quem excluiu e quando, pelo prazo da política de privacidade.',
      'A Lei Geral de Proteção de Dados garante pedir acesso, correção e eliminação dos seus dados.',
    ],
    example: null,
    calculation: null,
    hypotheses: null,
    facts: [],
    keywords: ['excluir conta', 'lgpd', 'privacidade', 'eliminação'],
    related: ['quem-ve-meus-dados', 'empresa-ve'],
    sources: [
      clarevo('D-007'),
      planalto(
        'Lei Geral de Proteção de Dados Pessoais (Lei nº 13.709/2018)',
        'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm',
        'art. 18, II (acesso), III (correção), IV e VI (eliminação)',
      ),
    ],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: 12,
    pending: ['Definir o canal de pedidos de titular (P-023) e trocar {canal de P-023} no resumo.'],
  },
  {
    slug: 'o-que-o-clarevo-nao-faz',
    section: 'duvidas',
    kind: 'pergunta',
    status: 'publicado',
    title: 'O Clarevo se conecta ao meu banco ou indica investimentos?',
    subtitle: null,
    question: null,
    short: 'Não. O Clarevo funciona com o que você anota: não pede senha de banco, não movimenta dinheiro, não oferece crédito e não indica investimentos.',
    paragraphs: [
      'Se alguém pedir a senha do seu banco em nome do Clarevo, não informe.',
      'Os conteúdos de Aprender são educativos e gerais, com exemplos fictícios. Para orientação individual, procure profissionais autorizados.',
      'As calculadoras fazem contas com os valores e as taxas que você digita e não indicam produto.',
    ],
    example: null,
    calculation: null,
    hypotheses: null,
    facts: [],
    keywords: ['integração bancária', 'senha do banco', 'investimentos', 'crédito', 'open finance'],
    related: ['liquidez-risco-retorno', 'quem-ve-meus-dados'],
    sources: [clarevo('D-008', 'D-023', 'D-034')],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: null,
  },
];
