import { CARDS_TEXT } from '../../cards';
import type { Topic } from '../types';
import {
  ANEEL_REN_1000,
  BCB_GLOSSARIO,
  CALC_CIDADAO_FINANCIAMENTO,
  CARDS_REVIEWED_ON,
  DECRETO_6306_CAMARA,
  PROCON_GO_ROTATIVO,
  RES_4881,
  REVIEWED_ON,
  bcb,
  cdc,
  clarevo,
  cmn,
  oficial,
  planalto,
} from './common';

/**
 * Seção "Juros e crédito" (Anexo A, temas 6 a 17, e "Taxa, tarifa e encargo" de spec3 §3.4), com os ajustes da
 * conferência de fontes de 09/10/2026. Nenhum tema oferece crédito, indica produto ou cita programa de renegociação.
 */
export const JUROS_TOPICS: Topic[] = [
  {
    slug: 'juros-simples-compostos',
    section: 'juros',
    kind: 'tema',
    status: 'publicado',
    title: 'Juros simples e juros compostos',
    subtitle: 'Por que uma dívida cresce mais rápido com o tempo',
    question: 'O que são juros compostos?',
    short:
      'Juros são o preço do dinheiro no tempo. Nos compostos, os juros de cada mês entram no saldo e passam a render juros, por isso o prazo pesa.',
    paragraphs: [
      'Juros são o preço do dinheiro no tempo: quem toma emprestado paga, e quem empresta ou aplica recebe. A taxa diz quanto, em percentual, por período, como ao mês ou ao ano.',
      'Nos juros simples, a taxa incide só sobre o valor inicial. Nos compostos, os juros de cada mês entram no saldo e passam a render juros no mês seguinte.',
      'Empréstimos, financiamentos e aplicações costumam usar juros compostos, e a Calculadora do Cidadão, do Banco Central, também usa juros compostos nas contas de financiamento. Por isso o tempo pesa: quanto mais longo o prazo, maior a diferença.',
    ],
    example:
      'R$ 1.000,00 a 2% ao mês por 12 meses viram R$ 1.240,00 com juros simples e R$ 1.268,24 com juros compostos. A diferença é de R$ 28,24.',
    calculation:
      'Simples: 1.000,00 × (1 + 0,02 × 12) = 1.240,00 · Compostos: 1.000,00 × 1,02^12 = 1.268,2418 → 1.268,24 · 1.268,24 - 1.240,00 = 28,24.',
    hypotheses: 'Taxa fictícia e constante, sem pagamentos no período, impostos ou tarifas.',
    facts: [],
    keywords: ['juros', 'juros sobre juros', 'capitalização', 'taxa de juros'],
    related: ['taxa-mes-ano', 'cet', 'inflacao-ipca'],
    sources: [
      BCB_GLOSSARIO('Verbetes "juros", "juros simples" e "juros compostos"; a maioria das operações usa juros compostos'),
      CALC_CIDADAO_FINANCIAMENTO('"Cálculo com juros compostos e capitalização mensal"'),
    ],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: 12,
    aliases: ['juros', 'juros-compostos'],
    calculator: { slug: 'custo-da-divida', params: {} },
  },
  {
    slug: 'taxa-mes-ano',
    section: 'juros',
    kind: 'tema',
    status: 'publicado',
    title: 'Taxa ao mês e taxa ao ano',
    subtitle: 'Por que 2% ao mês não é 24% ao ano',
    question: 'Como converter taxa ao mês em taxa ao ano?',
    short: 'Com juros compostos, 2% ao mês equivalem a 26,82% ao ano, não a 24%. Para comparar duas taxas, as duas precisam estar no mesmo período.',
    paragraphs: [
      'Ofertas de crédito costumam destacar a taxa ao mês. O Código de Defesa do Consumidor exige informar também a taxa efetiva anual (art. 52), e o CET é expresso ao ano (art. 54-B). Para comparar duas taxas, as duas precisam estar no mesmo período.',
      'Com juros compostos, a taxa ao ano não é a mensal vezes 12. A conta é: 1 mais a taxa ao mês, elevado a 12, menos 1. No sentido inverso, 12% ao ano equivalem a cerca de 0,95% ao mês, e não a 1%.',
      'A Calculadora do Cidadão, do Banco Central, faz contas de financiamento e de depósitos com taxa mensal e juros compostos.',
    ],
    example: '2% ao mês equivalem a 26,82% ao ano. Em 12 meses, R$ 1.000,00 viram R$ 1.268,24: R$ 268,24 de juros, ou 26,82%.',
    calculation: '1,02^12 - 1 = 0,268242 → 26,82% ao ano · 1.000,00 × 1,02^12 = 1.268,24 · No sentido inverso: 1,12^(1/12) - 1 = 0,009489 → 0,95% ao mês.',
    hypotheses: 'Taxas fictícias e constantes, juros compostos mensais.',
    facts: [],
    keywords: ['taxa anual', 'taxa mensal', 'juros ao ano', 'juros ao mês', 'taxa equivalente', 'juros'],
    related: ['juros-simples-compostos', 'cet', 'cheque-especial'],
    sources: [
      cdc('art. 52, II (taxa efetiva anual de juros), e art. 54-B, § 2º (CET em taxa percentual anual)'),
      CALC_CIDADAO_FINANCIAMENTO('Juros compostos, capitalização mensal e taxa de juros mensal'),
      bcb(
        'Calculadora do Cidadão: metodologia da aplicação com depósitos regulares',
        'https://www3.bcb.gov.br/CALCIDADAO/publico/exibirMetodologiaAplicacaoDepositosRegulares.do?method=exibirMetodologiaAplicacaoDepositosRegulares',
        'Fórmula com taxa de juros mensal e número de meses',
      ),
    ],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: 12,
    aliases: ['taxa-mensal-anual'],
    calculator: { slug: 'custo-da-divida', params: {} },
  },
  {
    slug: 'taxa-e-tarifa',
    section: 'juros',
    kind: 'tema',
    status: 'publicado',
    title: 'Taxa, tarifa e encargo',
    subtitle: 'Três palavras que aparecem no extrato',
    question: 'Qual a diferença entre taxa, tarifa e encargo?',
    short:
      'Taxa de juros é o preço do dinheiro no tempo. Tarifa é o preço de um serviço do banco. Quando uma conta atrasa, entram encargos como multa e juros de mora.',
    paragraphs: [
      'Tarifa é cobrada por serviço, como um pacote de conta. Na conta corrente, pessoas físicas têm direito a serviços essenciais sem tarifa, como o cartão de débito, até quatro saques e duas transferências entre contas do mesmo banco por mês e consultas pela internet. Acima disso, o banco pode cobrar por serviço ou por pacote.',
      'Quando uma conta atrasa, entram encargos: multa, juros de mora e, em algumas contas, correção.',
      'No Clarevo, tarifa, juros ou encargo que saiu da sua conta é um gasto: anote com a data da cobrança.',
    ],
    example: null,
    calculation: null,
    hypotheses: null,
    facts: [],
    keywords: ['tarifa bancária', 'pacote de serviços', 'serviços essenciais', 'encargos', 'extrato', 'cobrança do banco'],
    related: ['cet', 'iof-credito', 'multa-juros-atraso'],
    sources: [
      cmn(
        'Resolução CMN nº 3.919/2010 (tarifas), texto consolidado',
        'https://normativos.bcb.gov.br/Lists/Normativos/Attachments/49514/Res_3919_v7_P.pdf',
        'art. 1º (tarifa) e art. 2º, I (serviços essenciais da conta de depósitos à vista: cartão de débito, até quatro saques, até duas transferências entre contas na própria instituição por mês, consultas pela internet)',
      ),
      oficial(
        'Governo Federal',
        'Entenda quais tarifas podem ou não ser cobradas dos clientes',
        'https://www.gov.br/pt-br/noticias/financas-impostos-e-gestao-publica/2021/12/entenda-quais-tarifas-podem-ou-nao-ser-cobradas-dos-clientes',
        'Serviços essenciais gratuitos até uma quantidade máxima; acima dela, cobrança pelo uso a mais',
      ),
      BCB_GLOSSARIO('Verbete "juros": o custo de "deslocar" o dinheiro no tempo'),
      cdc('art. 52, § 1º (multa de mora)'),
      ANEEL_REN_1000('art. 343 (multa, atualização pelo IPCA e juros de mora na conta de luz)'),
    ],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: 12,
  },
  {
    slug: 'cet',
    section: 'juros',
    kind: 'tema',
    status: 'publicado',
    title: 'CET, o Custo Efetivo Total',
    subtitle: 'O número que junta juros, tarifas, seguros e impostos',
    question: 'O que é CET?',
    short: 'O CET reúne, numa taxa ao ano, juros, tributos, tarifas, seguros e outras despesas de um crédito. Para ofertas de mesmo valor e prazo, compare o CET.',
    paragraphs: [
      'A taxa de juros não mostra tudo o que um crédito custa. O CET reúne, numa taxa ao ano, os juros, os tributos (como o IOF), as tarifas, os seguros e outras despesas cobradas.',
      'Pela Resolução CMN nº 4.881/2020, a instituição precisa informar o CET antes da contratação, com um demonstrativo do valor de cada item, e esse demonstrativo precisa constar do contrato, em destaque. Desde 2021, o Código de Defesa do Consumidor também exige o CET na oferta de crédito e na venda a prazo (art. 54-B).',
      'Para comparar ofertas com o mesmo valor e o mesmo prazo, compare o CET, e não só a taxa de juros.',
    ],
    example:
      'Um crédito de R$ 5.000,00 em 12 parcelas de R$ 472,80 tem juros de 2% ao mês (26,82% ao ano). Com tarifa de cadastro de R$ 150,00 e seguro de R$ 100,00 descontados na liberação, chegam R$ 4.750,00 à conta. O CET fica em 2,85% ao mês, ou 40,03% ao ano.',
    calculation:
      'Parcela: 5.000,00 × 0,02 ÷ (1 - 1,02^-12) = 472,80 · Taxa que iguala 4.750,00 ao valor presente de 12 × 472,80: 2,8453% ao mês · 1,028453^12 - 1 = 0,4003 → 40,03% ao ano · Total pago: 12 × 472,80 = 5.673,60; custo sobre o valor recebido: 5.673,60 - 4.750,00 = 923,60.',
    hypotheses:
      'Exemplo fictício: parcelas mensais iguais, a primeira 30 dias depois; sem IOF, para mostrar só o efeito da tarifa e do seguro; meses iguais; o cálculo oficial usa as datas exatas, em base anual de 365 dias, e o número pode variar um pouco.',
    facts: [],
    keywords: ['custo efetivo total', 'custo do crédito', 'empréstimo', 'comparar ofertas', 'demonstrativo'],
    related: ['iof-credito', 'taxa-mes-ano', 'parcelado-ou-a-vista'],
    sources: [
      RES_4881('arts. 3º e 4º (componentes do CET; taxa percentual anual), art. 7º (informar antes da contratação, demonstrativo de cálculo destacado no contrato) e vigência desde 01/02/2021'),
      planalto(
        'Lei nº 14.181/2021 (inclui o art. 54-B no Código de Defesa do Consumidor)',
        'https://planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/l14181.htm',
        'art. 54-B, I (custo efetivo total na oferta de crédito e na venda a prazo)',
      ),
    ],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: 12,
    calculator: { slug: 'custo-da-divida', params: { modo: 'emprestimo' } },
  },
  {
    slug: 'iof-credito',
    section: 'juros',
    kind: 'tema',
    status: 'publicado',
    title: 'IOF no crédito',
    subtitle: 'O imposto que entra no custo de empréstimos',
    question: 'Quanto é o IOF de um empréstimo?',
    short:
      'Imposto federal que entra no custo do crédito. Para pessoas físicas: 0,38% sobre o valor, uma vez, e 0,0082% por dia de prazo, até 365 dias.',
    paragraphs: [
      'O IOF é um imposto federal sobre operações de crédito, câmbio, seguros e títulos. No crédito para pessoas físicas, ele tem duas partes: 0,38% sobre o valor, cobrados uma vez, e 0,0082% por dia de prazo, contados até 365 dias.',
      'Por isso, num crédito pago de uma vez em 1 ano ou mais, o IOF fica perto de 3,37% do valor. No cheque especial, a parte diária é calculada sobre o saldo negativo de cada dia.',
      'O IOF entra no CET e fica fora do limite de juros do rotativo do cartão.',
    ],
    example: 'Num crédito de R$ 2.000,00 pago de uma vez em 90 dias, o IOF é de R$ 22,36: R$ 7,60 da parte fixa e R$ 14,76 da parte diária.',
    calculation:
      '2.000,00 × 0,38% = 7,60 · 2.000,00 × 0,0082% × 90 = 14,76 · 7,60 + 14,76 = 22,36 (1,12% do valor) · Teto em 365 dias: 0,38% + 0,0082% × 365 = 3,373%.',
    hypotheses:
      'Exemplo fictício: pessoa física, pagamento único no fim do prazo; alíquotas vigentes em 09/10/2026 segundo as fontes consultadas. Em crédito parcelado, a parte diária incide sobre cada parcela de amortização pelo seu prazo, e o total fica menor.',
    facts: [
      { text: '0,38%', source: 1 },
      { text: '0,0082%', source: 0 },
    ],
    keywords: ['imposto', 'imposto sobre operações financeiras', 'empréstimo', 'alíquota'],
    related: ['cet', 'cheque-especial'],
    sources: [
      DECRETO_6306_CAMARA('art. 7º, I, "b", item 2 (mutuário pessoa física: 0,0082% ao dia, redação do Decreto nº 8.392/2015); art. 7º, I, "a" (saldos devedores diários)'),
      oficial(
        'Câmara dos Deputados',
        'Decreto nº 12.499/2025 (publicação original)',
        'https://www2.camara.leg.br/legin/fed/decret/2025/decreto-12499-11-junho-2025-797588-publicacaooriginal-175631-pe.html',
        'art. 7º, § 15, do Decreto nº 6.306/2007: alíquota adicional de 0,38%, seja o mutuário pessoa jurídica ou pessoa física',
      ),
      oficial(
        'Ministério da Fazenda',
        'Apresentação sobre o IOF (maio de 2025)',
        'https://www.gov.br/fazenda/pt-br/central-de-conteudo/publicacoes/apresentacoes/2025/Maio/iof-maio-2025.pdf',
        'A alíquota diária só incide pelo prazo máximo de 1 ano; nada muda nas operações de crédito de pessoas físicas',
      ),
      RES_4881('art. 3º: o CET considera tributos'),
      PROCON_GO_ROTATIVO('O custo do IOF está fora do cálculo do limite'),
    ],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: 6,
  },
  {
    slug: 'parcelado-ou-a-vista',
    section: 'juros',
    kind: 'tema',
    status: 'publicado',
    title: 'Parcelado, sem juros ou à vista',
    subtitle: 'Como descobrir os juros embutidos',
    question: 'Parcelado "sem juros" tem juros?',
    short: 'Quando há desconto à vista, o parcelado "sem juros" tem um custo: a diferença entre o total parcelado e o preço à vista.',
    paragraphs: [
      'Quando a loja dá desconto à vista, o parcelado "sem juros" passa a ter um custo: a diferença entre o total parcelado e o preço à vista. Se os dois forem iguais, não há juros embutidos. A lei permite preços diferentes conforme o prazo ou a forma de pagamento, e a loja precisa informar esses descontos em local e formato visíveis (Lei nº 13.455/2017).',
      'Na venda a prazo com crédito, o Código de Defesa do Consumidor (art. 52) exige informar antes o preço em reais, os juros de mora e a taxa efetiva anual de juros, os acréscimos previstos em lei, o número e a periodicidade das parcelas e a soma total a pagar, com e sem financiamento.',
      'Para comparar, descubra a taxa que transforma o preço à vista nas parcelas. Na Calculadora do Cidadão, do Banco Central, informe o preço à vista como valor financiado, o número de parcelas e o valor de cada uma; ela calcula a taxa ao mês, considerando a primeira parcela fora do ato da compra.',
    ],
    example:
      'Uma compra de R$ 1.200,00 sai em 10 parcelas de R$ 120,00 "sem juros" ou por R$ 1.080,00 à vista. Parcelar custa R$ 120,00 a mais, o que equivale a juros de 1,96% ao mês (26,27% ao ano). Se a primeira parcela for paga no ato da compra, a taxa embutida sobe para 2,42% ao mês (33,28% ao ano).',
    calculation:
      'Taxa i tal que 1.080,00 = 120,00 × (1 - (1 + i)^-10) ÷ i → i = 1,9630% ao mês · 1,019630^12 - 1 = 26,27% ao ano · Com a 1ª parcela no ato: 1.080,00 - 120,00 = 960,00 financiados em 9 parcelas → i = 2,4227% ao mês · 1,024227^12 - 1 = 33,28% ao ano.',
    hypotheses: 'Exemplo fictício: parcelas mensais iguais, a primeira 30 dias depois da compra (salvo quando indicado), sem tarifas.',
    facts: [],
    keywords: ['desconto à vista', 'preço à vista', 'parcelar', 'compra parcelada', 'parcela'],
    related: ['cet', 'amortizacao-price-sac', 'juros-simples-compostos'],
    sources: [
      oficial(
        'Câmara dos Deputados',
        'Lei nº 13.455/2017 (publicação original)',
        'https://www2.camara.leg.br/legin/fed/lei/2017/lei-13455-26-junho-2017-785093-publicacaooriginal-153193-pl.html',
        'art. 1º: diferenciação de preços em função do prazo ou do instrumento de pagamento',
      ),
      oficial(
        'Senado Federal',
        'Lei nº 13.455/2017 (inclui o art. 5º-A na Lei nº 10.962/2004)',
        'https://legis.senado.leg.br/norma/17711076/publicacao/17711085',
        'art. 5º-A: informar, em local e formato visíveis, os descontos por prazo ou instrumento de pagamento',
      ),
      cdc('art. 52, I a V'),
      bcb(
        'Calculadora do Cidadão: financiamento com prestações fixas',
        'https://www3.bcb.gov.br/CALCIDADAO/publico/exibirFormFinanciamentoPrestacoesFixas.do?method=exibirFormFinanciamentoPrestacoesFixas',
        'Informe 3 valores para obter o 4º; a 1ª prestação não é no ato; o valor financiado não inclui a entrada',
      ),
    ],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: 12,
    calculator: { slug: 'parcelado-ou-a-vista', params: {} },
  },
  {
    slug: 'rotativo-cartao',
    section: 'juros',
    kind: 'tema',
    status: 'publicado',
    title: 'Rotativo do cartão e parcelamento da fatura',
    subtitle: 'O que acontece quando a fatura não é paga inteira',
    question: 'O que é o rotativo do cartão?',
    short:
      'O que fica sem pagar na fatura vira crédito rotativo, com juros. Para dívidas desde 3 de janeiro de 2024, juros e encargos não podem passar do valor original.',
    paragraphs: [
      'Se a fatura não é paga inteira no vencimento, o que falta vira crédito rotativo, com juros sobre esse saldo. Pelas regras do Conselho Monetário Nacional, o rotativo só pode durar até o vencimento da fatura seguinte; o saldo pode ir para outra forma de crédito, como o parcelamento da fatura, em condições mais vantajosas que as do rotativo (Resolução CMN nº 4.549/2017).',
      'Para dívidas que entraram no rotativo a partir de 3 de janeiro de 2024, a soma de juros e encargos (como multa, juros de mora e tarifas) do rotativo e do parcelamento da fatura não pode passar do valor original da dívida (Lei nº 14.690/2023 e Resolução CMN nº 5.112/2023). Assim, o total a pagar fica em até o dobro do valor que entrou no rotativo. O IOF fica fora desse limite.',
      'Quando o rotativo vira parcelamento, a conta do limite continua desde o início do rotativo, sem recomeçar. A fatura precisa mostrar o valor original e o total de juros e encargos de cada operação.',
      CARDS_TEXT.rotativoParagraph,
    ],
    example:
      'Numa fatura de R$ 1.000,00, você paga R$ 300,00 e R$ 700,00 vão para o rotativo. Com taxa fictícia de 14% ao mês, os juros do mês são R$ 98,00 e o saldo vai a R$ 798,00. Se esse saldo for parcelado em 24 vezes a 8% ao mês, as parcelas somariam R$ 1.818,96, com R$ 1.118,96 de juros desde o início. Pelo limite, juros e encargos param em R$ 700,00: sem IOF, quitar os R$ 700,00 que entraram no rotativo custa no máximo R$ 1.400,00.',
    calculation:
      '700,00 × 14% = 98,00 · 700,00 + 98,00 = 798,00 · Parcela: 798,00 × 0,08 ÷ (1 - 1,08^-24) = 75,79 · 24 × 75,79 = 1.818,96 · Juros: 98,00 + (1.818,96 - 798,00) = 1.118,96, acima do limite de 700,00 · Total máximo: 700,00 + 700,00 = 1.400,00 · Em 12 vezes, a parcela seria de 105,89, o total de 1.270,68 e os juros de 570,68, abaixo do limite.',
    hypotheses: 'Taxas fictícias; sem IOF, multa, atraso ou novas compras; dívida que entrou no rotativo a partir de 03/01/2024.',
    facts: [],
    keywords: ['cartão de crédito', 'fatura', 'pagamento mínimo', 'parcelamento da fatura', 'teto de juros'],
    related: ['fatura', 'cheque-especial', 'juros-simples-compostos'],
    sources: [
      clarevo('D-037'),
      planalto('Lei nº 14.690/2023', 'https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/lei/l14690.htm', 'art. 28, § 1º: juros e encargos financeiros limitados ao valor original da dívida'),
      cmn(
        'Resolução CMN nº 4.549/2017, texto consolidado com a Resolução CMN nº 5.112/2023',
        'https://normativos.bcb.gov.br/Lists/Normativos/Attachments/50330/Res_4549_v2_L.pdf',
        'art. 1º (rotativo até o vencimento da fatura seguinte), art. 2º (parcelamento em condições mais vantajosas), art. 2º-A (encargos financeiros; parágrafo único, I e II: valor original e contagem desde o início do rotativo) e art. 2º-B (valor original e encargos na fatura)',
      ),
      cmn(
        'Voto CMN nº 67/2023',
        'https://normativos.bcb.gov.br/Votos/CMN/202367/Voto_do_CMN_67_2023.pdf',
        'Os arts. 2º-A a 2º-C valem só para operações feitas depois do prazo de 90 dias do art. 28, § 1º, da Lei nº 14.690/2023',
      ),
      bcb(
        'Instruções de preenchimento do documento 3060 (juros acumulados do cartão)',
        'https://www.bcb.gov.br/content/estabilidadefinanceira/Leiaute_de_documentos/3060/Instrucoes-preenchimento-Juros-acumulados-cartao.pdf',
        'Operações iniciadas a partir de 3/1/2024',
      ),
      PROCON_GO_ROTATIVO('IOF fora do cálculo; dívida de R$ 100 não pode passar de R$ 200 com juros e encargos'),
    ],
    reviewedOn: CARDS_REVIEWED_ON,
    reviewEveryMonths: 6,
    aliases: ['cartao-rotativo'],
    calculator: { slug: 'custo-da-divida', params: { modo: 'rotativo' } },
  },
  {
    slug: 'cheque-especial',
    section: 'juros',
    kind: 'tema',
    status: 'publicado',
    title: 'Cheque especial',
    subtitle: 'Um limite na conta que cobra juros sobre o valor usado',
    question: 'Quanto custa usar o cheque especial?',
    short:
      'Limite de crédito ligado à conta: saldo negativo é empréstimo, com juros sobre o valor usado, mais IOF. Para pessoas físicas e MEIs, os juros têm teto de 8% ao mês.',
    paragraphs: [
      'O cheque especial é um limite de crédito ligado à conta. Quando o saldo fica negativo, a diferença é um empréstimo, com juros sobre o valor usado pelo tempo em que a conta fica negativa, conforme o contrato, mais IOF.',
      'Desde 6 de janeiro de 2020, os juros do cheque especial para pessoas físicas e MEIs estão limitados a 8% ao mês sobre o valor usado (Resolução CMN nº 4.765/2019). Com juros compostos, 8% ao mês equivalem a 151,82% ao ano.',
      'A cobrança de tarifa só por ter o limite, mesmo sem usar, foi declarada inconstitucional pelo Supremo Tribunal Federal (ADI 6.407).',
    ],
    example: 'Ficar R$ 500,00 no negativo por 30 dias, na taxa máxima de 8% ao mês, custa R$ 40,00 de juros, mais IOF.',
    calculation: '500,00 × 8% = 40,00 · 1,08^12 - 1 = 1,518170 → 151,82% ao ano.',
    hypotheses: 'Exemplo fictício: saldo negativo igual por 30 dias e taxa igual ao teto. A forma de contar os dias segue o contrato.',
    facts: [{ text: '8% ao mês', source: 0 }],
    keywords: ['limite da conta', 'saldo negativo', 'conta no vermelho', 'teto de juros'],
    related: ['taxa-mes-ano', 'saldo', 'iof-credito'],
    sources: [
      cmn(
        'Resolução CMN nº 4.765/2019, texto consolidado',
        'https://normativos.bcb.gov.br/Lists/Normativos/Attachments/50875/Res_4765_v2_P.pdf',
        'art. 1º (pessoas naturais e MEI; limite de crédito rotativo vinculado à conta), art. 3º (juros limitados a 8% ao mês sobre o valor utilizado), vigência em 6 de janeiro de 2020 e nota sobre a ADI 6.407 no art. 2º',
      ),
      oficial(
        'Governo Federal',
        'Já está valendo a limitação de juros para cheque especial (janeiro de 2020)',
        'https://www.gov.br/pt-br/noticias/financas-impostos-e-gestao-publica/2020/01/ja-esta-valendo-a-limitacao-de-juros-para-cheque-especial',
        'A Resolução 4.765, aprovada em novembro de 2019, começou a valer em janeiro de 2020',
      ),
      planalto(
        'Decreto nº 6.306/2007 (Regulamento do IOF), texto compilado',
        'https://planalto.gov.br/ccivil_03/_ato2007-2010/2007/decreto/d6306compilado.htm',
        'art. 7º, I, "a": crédito com reutilização prevista, base no somatório dos saldos diários',
      ),
      oficial(
        'Supremo Tribunal Federal',
        'ADI 6.407: cobrança de tarifa pela disponibilização de cheque especial',
        'https://portal.stf.jus.br/noticias/verNoticiaDetalhe.asp?idConteudo=465221&ori=1',
        'Mérito julgado procedente, com a declaração de inconstitucionalidade, em sessão virtual encerrada em 30/4/2021',
      ),
    ],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: 6,
    calculator: { slug: 'custo-da-divida', params: { modo: 'cheque_especial' } },
  },
  {
    slug: 'amortizacao-price-sac',
    section: 'juros',
    kind: 'tema',
    status: 'publicado',
    title: 'Amortização, Tabela Price e SAC',
    subtitle: 'Como a parcela se divide entre juros e dívida',
    question: 'Qual a diferença entre Tabela Price e SAC?',
    short:
      'Cada parcela tem juros e amortização. Na Tabela Price a parcela é igual do começo ao fim; no SAC a amortização é igual, e a parcela começa maior e diminui.',
    paragraphs: [
      'Cada parcela de um financiamento tem duas partes: os juros, calculados sobre o saldo que falta, e a amortização, que reduz esse saldo. O sistema de amortização define como essa divisão muda ao longo do tempo.',
      'Na Tabela Price, a parcela é igual do começo ao fim: no início, a maior parte é juros; no fim, quase tudo é amortização. No SAC (Sistema de Amortização Constante), a amortização é a mesma todo mês e os juros caem, então a parcela começa maior e diminui.',
      'Com a mesma taxa e o mesmo prazo, o SAC soma menos juros, porque o saldo cai mais rápido; a Price tem parcelas iniciais menores. Em contratos corrigidos pela inflação, as parcelas podem subir nos dois sistemas.',
    ],
    example:
      'Num financiamento de R$ 12.000,00 em 12 meses a 1% ao mês, a Price tem 12 parcelas de R$ 1.066,19, com R$ 794,28 de juros no total; na primeira, R$ 120,00 são juros e R$ 946,19 são amortização. No SAC, a amortização é de R$ 1.000,00 por mês, a primeira parcela é de R$ 1.120,00, a última de R$ 1.010,00, e os juros somam R$ 780,00.',
    calculation:
      'Price: 12.000,00 × 0,01 ÷ (1 - 1,01^-12) = 1.066,19 · 12 × 1.066,19 = 12.794,28 · 12.794,28 - 12.000,00 = 794,28 · SAC: juros = 1% × (12.000,00 + 11.000,00 + ... + 1.000,00) = 1% × 78.000,00 = 780,00 · 1ª parcela: 1.000,00 + 120,00 = 1.120,00 · 12ª: 1.000,00 + 10,00 = 1.010,00.',
    hypotheses: 'Exemplo fictício: taxa fixa, sem seguros, tarifas, IOF ou correção monetária; sem ajuste de centavos na última parcela da Price.',
    facts: [],
    keywords: ['tabela price', 'sistema francês', 'sac', 'amortização constante', 'financiamento', 'juros no parcelamento'],
    related: ['parcelamentos', 'quitar-antes'],
    sources: [
      bcb(
        'Calculadora do Cidadão: financiamento com prestações fixas (metodologia)',
        'https://www.bcb.gov.br/pec/calculo/calc_financiamento/metodologia.asp?frame=1',
        '"Cálculo com juros compostos e capitalização mensal"; fórmula da prestação fixa',
      ),
      bcb(
        'Calculadora do Cidadão: ajuda',
        'https://www3.bcb.gov.br/CALCIDADAO/publico/ajudaCartaoCredito.do',
        'Parcelas fixas, "similar ao método da tabela Price (ou sistema francês)", com juros decrescentes',
      ),
      bcb(
        'Nota Técnica nº 56: Estabilizando a prestação nominal em contratos (outubro de 2025)',
        'https://www.bcb.gov.br/content/publicacoes/notastecnicas/NT_56_202510.pdf',
        'Price com prestação nominal constante, maior parte de juros no início; prestações de contratos corrigidos sensíveis à inflação',
      ),
      oficial(
        'Tribunal de Contas do Município de São Paulo, Escola de Contas',
        'Sistemas de Amortização de Financiamentos: SAC, PRICE',
        'https://egcportalantigo.tcm.sp.gov.br/artigos/1705-sistemas-de-amortizacao-de-financiamentos-sac-price',
        'Prestação = amortização + juros; SAC com amortização constante, juros e prestação decrescentes; o SAC amortiza a dívida de forma mais rápida',
      ),
      oficial(
        'Tribunal Regional Federal da 3ª Região',
        'Acórdão sobre Tabela Price e SAC (busca de jurisprudência)',
        'https://web.trf3.jus.br/acordaos/Acordao/BuscarDocumentoPje/262326291',
        'A Tabela Price implica pagamento total maior de juros, decorrência de uma prestação constante e inicialmente inferior à do SAC',
      ),
    ],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: 12,
    aliases: ['juros-no-parcelamento'],
  },
  {
    slug: 'quitar-antes',
    section: 'juros',
    kind: 'tema',
    status: 'publicado',
    title: 'Quitar antes do prazo',
    subtitle: 'O que a soma das parcelas não mostra',
    question: 'Tenho desconto se pagar parcelas antes?',
    short:
      'O Código de Defesa do Consumidor garante quitar antes, no todo ou em parte, com redução proporcional dos juros. Peça à instituição o valor atualizado para quitação.',
    paragraphs: [
      'O Código de Defesa do Consumidor (art. 52, § 2º) garante quitar uma dívida antes do prazo, no todo ou em parte, com redução proporcional dos juros e demais acréscimos.',
      'Em contratos de crédito de pessoas físicas com taxa prefixada, o valor para quitar é o valor presente das parcelas que faltam, calculado com a taxa de juros do próprio contrato (Resolução CMN nº 5.004/2022). Linhas com recursos direcionados ou taxas administradas, como o crédito rural e o financiamento pelo Sistema Financeiro da Habitação, podem seguir outra regra.',
      'Bancos e financeiras não podem cobrar tarifa por quitar antes em contratos de pessoas físicas assinados a partir de 10 de dezembro de 2007 (Resolução CMN nº 3.516/2007). A oferta de crédito também precisa informar o direito de quitar antes sem custo extra (Código de Defesa do Consumidor, art. 54-B).',
      'Peça à instituição o valor atualizado para quitação; ele costuma ser menor que a soma das parcelas. Numa quitação parcial, as parcelas mais distantes são as que têm o maior desconto. Na calculadora do Clarevo, você vê uma estimativa com a taxa que digitar; o valor oficial é o que a instituição informar.',
    ],
    example:
      'Faltam 36 parcelas de R$ 850,00, que somam R$ 30.600,00, com taxa de 1,5% ao mês no contrato. Para quitar tudo hoje, o valor seria R$ 23.511,58, um desconto de R$ 7.088,42. Antecipar só as 3 últimas custaria R$ 1.514,47, em vez de R$ 2.550,00.',
    calculation:
      '36 × 850,00 = 30.600,00 · Valor presente: 850,00 × (1 - 1,015^-36) ÷ 0,015 = 23.511,58 · 30.600,00 - 23.511,58 = 7.088,42 · Três últimas: 850,00 ÷ 1,015^34 + 850,00 ÷ 1,015^35 + 850,00 ÷ 1,015^36 = 1.514,47.',
    hypotheses: 'Exemplo fictício: taxa prefixada, próxima parcela em 1 mês, sem IOF, seguros ou tarifas. O valor real é o informado pela instituição.',
    facts: [],
    keywords: ['quitação antecipada', 'liquidação antecipada', 'adiantar parcelas', 'desconto', 'valor presente', 'antecipar'],
    related: ['parcelamentos', 'amortizacao-price-sac', 'cet'],
    sources: [
      cdc('art. 52, § 2º (liquidação antecipada com redução proporcional dos juros) e art. 54-B (liquidação antecipada e não onerosa informada na oferta)'),
      cmn(
        'Resolução CMN nº 3.516/2007, texto consolidado',
        'https://normativos.bcb.gov.br/Lists/Normativos/Attachments/48006/Res_3516_v3_L.pdf',
        'art. 1º (vedada a tarifa por liquidação antecipada em contratos com pessoas físicas, microempresas e empresas de pequeno porte); arts. 2º e 3º revogados desde 2/5/2022 pela Resolução CMN nº 5.004/2022',
      ),
      cmn(
        'Resolução CMN nº 3.516/2007, texto original',
        'https://www.bcb.gov.br/pre/normativos/res/2007/pdf/res_3516_v1_o.pdf',
        'Vigência na data da publicação; recursos direcionados e taxas administradas fora da regra de cálculo',
      ),
      oficial(
        'Superior Tribunal de Justiça',
        'Informativo de Jurisprudência nº 597 (REsp 1.370.144-SP)',
        'https://processo.stj.jus.br/jurisprudencia/externo/informativo/?livre=@CNOT%3D016192',
        'Tarifa de liquidação antecipada: contratos celebrados antes de 10/12/2007, data da publicação da Resolução CMN nº 3.516/2007',
      ),
      cmn(
        'Voto CMN nº 33/2022 (texto aprovado da Resolução CMN nº 5.004/2022)',
        'https://normativos.bcb.gov.br/Votos/CMN/202233/Voto_do_CMN_33_2022.pdf',
        'art. 7º: taxa de juros pactuada no contrato para o valor presente na liquidação antecipada, em operações prefixadas; exceção para recursos direcionados ou taxas administradas',
      ),
      clarevo('D-024', 'D-034'),
    ],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: 12,
    calculator: { slug: 'quitar-antes', params: {} },
  },
  {
    slug: 'multa-juros-atraso',
    section: 'juros',
    kind: 'tema',
    status: 'publicado',
    title: 'Multa e juros por atraso',
    subtitle: 'O que pode ser cobrado depois do vencimento',
    question: 'Quanto podem cobrar se eu atrasar uma conta?',
    short:
      'Em compras e serviços com crédito ou parcelamento, a multa por atraso não pode passar de 2% da prestação. Juros de mora e correção dependem da regra de cada conta.',
    paragraphs: [
      'Em compras e serviços com crédito ou parcelamento, a multa por atraso não pode passar de 2% do valor da prestação (Código de Defesa do Consumidor, art. 52, § 1º). Além da multa, podem entrar juros de mora e correção, quando previstos. Outras contas têm regras próprias.',
      'Na conta de luz, a regra da ANEEL permite multa de até 2%, juros de mora de 1% ao mês proporcionais aos dias de atraso e correção pelo IPCA. Se o vencimento cair em sábado, domingo ou feriado, pagar no primeiro dia útil seguinte não é atraso.',
      'No condomínio, o Código Civil prevê multa de até 2% e os juros e a correção da convenção; sem previsão, valem a taxa legal (Selic menos IPCA, nunca abaixo de zero) e a correção pelo IPCA, regra em vigor desde agosto de 2024.',
    ],
    example:
      'Uma conta de luz de R$ 200,00 paga 10 dias depois do vencimento tem multa de R$ 4,00 e juros de R$ 0,67. O total fica em R$ 204,67, mais a correção pelo IPCA.',
    calculation: '200,00 × 2% = 4,00 · 200,00 × 1% × 10 ÷ 30 = 0,666... → 0,67 · 200,00 + 4,00 + 0,67 = 204,67.',
    hypotheses:
      'Exemplo fictício: mês de 30 dias; fatura só com o consumo de energia, sem contribuição de iluminação pública ou outras cobranças; correção pelo IPCA não incluída; cobrança na fatura seguinte.',
    facts: [
      { text: '2% do valor da prestação', source: 0 },
      { text: 'multa de até 2%', source: 1 },
      { text: '1% ao mês', source: 1 },
    ],
    keywords: ['multa', 'juros de mora', 'atraso', 'conta vencida', 'conta de luz', 'condomínio', 'taxa legal'],
    related: ['marcar-como-paga', 'rotativo-cartao', 'cheque-especial'],
    sources: [
      cdc('art. 52, § 1º, com redação da Lei nº 9.298/1996'),
      ANEEL_REN_1000('art. 343 (multa de até 2%, IPCA e juros de mora de 1% ao mês pro rata die; vencimento em sábado, domingo ou feriado), com a redação da REN nº 1.115/2025'),
      planalto(
        'Lei nº 14.905/2024',
        'https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/lei/l14905.htm',
        'Nova redação do Código Civil: art. 389, parágrafo único (IPCA), art. 406, § 1º (taxa legal: Selic menos o IPCA) e art. 1.336, § 1º (condomínio: multa de até 2%)',
      ),
      bcb(
        'Calculadora do Cidadão: metodologia da taxa legal (Resolução CMN nº 5.171/2024)',
        'https://www3.bcb.gov.br/CALCIDADAO/publico/metodologiaCorrigirPelaTaxaLegal.do?method=metodologiaCorrigirPelaTaxaLegal',
        'Valores negativos: a taxa legal do mês é zero',
      ),
    ],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: 12,
    aliases: ['atraso'],
    calculator: { slug: 'multa-e-juros', params: {} },
  },
  {
    slug: 'score-credito',
    section: 'juros',
    kind: 'tema',
    status: 'publicado',
    title: 'Score de crédito',
    subtitle: 'O que é a nota e o que a lei garante',
    question: 'Como funciona o score de crédito?',
    short:
      'Nota calculada por empresas de dados de crédito para estimar a chance de pagar em dia. A lei garante consultar de graça a nota e o histórico e conhecer os principais critérios usados.',
    paragraphs: [
      'Score é uma nota calculada por empresas de banco de dados de crédito para estimar a chance de uma pessoa pagar em dia. Mais de uma empresa calcula essa nota.',
      'Desde a Lei Complementar nº 166/2019, a inclusão no Cadastro Positivo é automática: o histórico de contas e créditos pagos pode compor a nota. Você pode pedir, de graça, o cancelamento ou a reabertura do cadastro.',
      'A Lei nº 12.414/2011 garante consultar de graça a sua nota e o seu histórico e conhecer os principais critérios usados, respeitado o segredo empresarial. Dados de origem social e étnica, saúde, informação genética, sexo e convicções políticas, religiosas ou filosóficas não podem entrar na nota.',
      'Para ver os empréstimos e financiamentos registrados no seu CPF, o Banco Central oferece o Registrato, gratuito. O Clarevo não calcula nem prevê score.',
    ],
    example:
      'Das 12 contas pagas nos últimos 12 meses, 11 foram pagas em dia: 91,7% no prazo. Esse é um dado do histórico; a lei protege o segredo empresarial do cálculo, e nenhuma ação garante uma nota específica.',
    calculation: '11 ÷ 12 = 0,91666... → 91,7%.',
    hypotheses: 'Exemplo fictício. Não simula nem estima nota de crédito.',
    facts: [],
    keywords: ['pontuação de crédito', 'nota de crédito', 'cadastro positivo', 'registrato', 'histórico de pagamentos'],
    related: ['superendividamento', 'o-que-o-clarevo-nao-faz'],
    sources: [
      planalto(
        'Lei nº 12.414/2011 (Cadastro Positivo)',
        'https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12414.htm',
        'art. 5º, I e § 4º (cancelamento e reabertura gratuitos), II (acesso gratuito ao histórico e à nota) e IV (principais elementos e critérios, resguardado o segredo empresarial); art. 7º-A, I (informações vedadas na nota)',
      ),
      oficial(
        'Banco Central do Brasil, Revista da PGBC',
        'Cadastro Positivo: a solução para o combate à assimetria informacional',
        'https://revistapgbc.bcb.gov.br/index.php/revista/article/download/1016/31/',
        'Direito do cadastrado de conhecer os principais elementos e critérios considerados para a análise de risco',
      ),
      planalto('Lei Complementar nº 166/2019', 'https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp166.htm'),
      bcb(
        'Cadastro Positivo: análise dos efeitos do novo modelo',
        'https://www.bcb.gov.br/content/publicacoes/Documents/outras_pub_alfa/analise_dos_efeitos_do_cadastro_positivo.pdf',
        'A situação padrão passa a ser estar dentro do Cadastro Positivo',
      ),
      oficial(
        'Governo Federal',
        'Cadastro Positivo já está no ar (janeiro de 2020)',
        'https://www.gov.br/pt-br/noticias/financas-impostos-e-gestao-publica/2020/01/cadastro-positivo-ja-esta-no-ar',
        'O Cadastro Positivo funciona como um histórico: quanto mais pontual com as contas, maior a nota',
      ),
      oficial(
        'Governo Federal',
        'Emitir Relatório de Empréstimos e Financiamentos (SCR)',
        'https://www.gov.br/pt-br/servicos/obter-relatorio-do-sistema-de-informacoes-de-credito-scr',
        'Acesso pelo Registrato, sem custo; empréstimos e financiamentos em dia ou em atraso',
      ),
      oficial(
        'Procon Niterói',
        'Difícil tomar empréstimo? Problema pode ser o score de crédito (abril de 2024)',
        'https://procon.niteroi.rj.gov.br/2024/04/02/dificil-tomar-emprestimo-problema-pode-ser-o-score-de-credito-veja-como-seu-risco-e-avaliado-e-saiba-como-melhorar-a-nota/',
        'Cinco empresas têm permissão para calcular score no país',
      ),
    ],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: 12,
  },
  {
    slug: 'superendividamento',
    section: 'juros',
    kind: 'tema',
    status: 'publicado',
    title: 'Quando as dívidas não cabem na renda',
    subtitle: 'O que a lei do superendividamento prevê',
    question: 'O que é superendividamento?',
    short:
      'Situação de quem, de boa-fé, não consegue pagar as dívidas de consumo sem comprometer o mínimo para viver, hoje de R$ 600,00 por mês. A lei permite pedir a repactuação.',
    paragraphs: [
      'A lei chama de superendividamento a situação de quem, de boa-fé, não consegue pagar as dívidas de consumo sem comprometer o mínimo para viver (Lei nº 14.181/2021, que alterou o Código de Defesa do Consumidor).',
      'Esse mínimo, chamado mínimo existencial, é de R$ 600,00 por mês desde junho de 2023 (Decreto nº 11.150/2022, com redação do Decreto nº 11.567/2023). Em abril de 2026, o Supremo Tribunal Federal determinou que esse valor seja reavaliado todo ano.',
      'A lei permite pedir a repactuação das dívidas, reunindo as empresas credoras num plano de pagamento de até 5 anos que preserve esse mínimo. Ficam fora, entre outras, dívidas de financiamento imobiliário, de crédito rural e com garantia real. Procons e Defensorias Públicas podem orientar como pedir.',
    ],
    example: 'Com renda de R$ 2.000,00 e R$ 1.700,00 em parcelas de dívidas de consumo no mês, sobram R$ 300,00, abaixo do mínimo existencial de R$ 600,00.',
    calculation: '2.000,00 - 1.700,00 = 300,00 · 300,00 < 600,00.',
    hypotheses: 'Exemplo fictício. O enquadramento depende da análise de cada caso e das dívidas que entram na conta.',
    facts: [{ text: 'R$ 600,00', source: 2 }],
    keywords: ['mínimo existencial', 'repactuação', 'dívidas', 'renegociar', 'procon', 'defensoria'],
    related: ['score-credito', 'rotativo-cartao', 'cheque-especial'],
    sources: [
      cdc('art. 54-A, § 1º (definição), art. 104-A, caput e § 1º (plano de até 5 anos; dívidas excluídas) e art. 104-C (órgãos de defesa do consumidor na fase conciliatória)'),
      planalto('Lei nº 14.181/2021', 'https://planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/l14181.htm', 'Altera o Código de Defesa do Consumidor'),
      planalto(
        'Decreto nº 11.567/2023',
        'https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/decreto/d11567.htm',
        'Mínimo existencial: renda mensal equivalente a R$ 600,00',
      ),
      oficial(
        'Planalto',
        'Presidente amplia mínimo existencial para R$ 600 (junho de 2023)',
        'https://www.gov.br/planalto/pt-br/acompanhe-o-planalto/noticias/2023/06/presidente-amplia-minimo-existencial-para-r-600',
        'Decreto publicado em 20/06/2023',
      ),
      planalto('Decreto nº 11.150/2022', 'https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2022/decreto/d11150.htm', 'Regulamenta o mínimo existencial'),
      oficial(
        'Supremo Tribunal Federal',
        'Informativo STF nº 1214 (ADPF 1.005, julgamento finalizado em 23/04/2026)',
        'https://www.stf.jus.br/arquivo/informativo/documento/informativo1214.htm',
        'Avaliação anual do valor do mínimo existencial; manutenção do valor fixado no momento',
      ),
      oficial(
        'Ministério da Justiça e Segurança Pública, Senacon',
        'Nota Técnica nº 11/2023',
        'https://www.gov.br/mj/pt-br/assuntos/seus-direitos/consumidor/notas-tecnicas/nota-tecnica-no-11-2023-cgemm-dpdc-senacon-mj.pdf',
        'Plano de pagamento com prazo máximo de 5 anos, preservado o mínimo existencial (art. 104-A)',
      ),
      oficial(
        'Defensoria Pública do Maranhão',
        'DPE/MA garante na Justiça renegociação de consumidora com superendividamento',
        'https://defensoria.ma.def.br/dpema/portal/noticias/9014/dpema-garante-na-justica-renegociacao-de-consumidora-com-superendividamento',
        'Quem tem o mínimo existencial comprometido pode procurar o Núcleo de Defesa do Consumidor da Defensoria para orientações',
      ),
    ],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: 12,
  },
];
