import type { Topic } from '../types';
import { REVIEWED_ON, clarevo } from './common';

/**
 * Seção "Usar o Clarevo": como cada número do app é calculado. Fontes: decisões do projeto (docs/00).
 * Os seis primeiros temas mantêm os textos publicados antes do A5 (lib/topics.ts); em `diferenca`, o parágrafo que
 * começava com "Exemplo:" passou para o campo `example`, com o mesmo texto.
 */
export const USAR_TOPICS: Topic[] = [
  {
    slug: 'diferenca',
    section: 'usar',
    kind: 'tema',
    status: 'publicado',
    title: 'Diferença do mês',
    subtitle: 'Como um registro entra no mês',
    question: 'Como um gasto ou recebimento entra no mês?',
    short: 'Recebido menos pago no mês, pela data em que o dinheiro entrou ou saiu. Não é o saldo da conta.',
    paragraphs: [
      'A diferença do mês é o total recebido menos o total pago no período. Entra no mês a data do pagamento ou do recebimento, não a data da compra.',
    ],
    example:
      'Com R$ 6.000 recebidos e R$ 3.900 pagos em outubro, a diferença é R$ 2.100. Um gasto de R$ 80 pago em 7 de outubro muda o total pago para R$ 3.980.',
    calculation: '6.000,00 - 3.900,00 = 2.100,00 · 3.900,00 + 80,00 = 3.980,00.',
    hypotheses: 'Exemplo fictício. Considera apenas registros realizados no mesmo contexto.',
    facts: [],
    keywords: ['resultado do mês', 'sobra do mês', 'recebido', 'pago', 'data do pagamento'],
    related: ['saldo', 'realizado-previsto'],
    sources: [clarevo('D-005', 'D-011')],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: null,
  },
  {
    slug: 'realizado-previsto',
    section: 'usar',
    kind: 'tema',
    status: 'publicado',
    title: 'Realizado e previsto',
    subtitle: 'O que já aconteceu e o que ainda vai acontecer',
    question: 'Por que uma conta a pagar não entra em Pago?',
    short: 'Realizado é o que já foi pago ou recebido. Previsto é uma conta a pagar que ainda não foi paga.',
    paragraphs: [
      'Realizado é o que já foi pago ou recebido. Previsto é uma conta a pagar que ainda não foi paga, como a internet que vence no dia 15.',
      'Contas a pagar aparecem em "Ainda a pagar neste mês" e não entram em Recebido, Pago ou na diferença do mês. Quando você marca uma conta como paga, o Clarevo registra um gasto com o valor e a data do pagamento, e só esse gasto entra em Pago, no mês da data do pagamento.',
      'Uma conta vencida e ainda não paga continua em "Ainda a pagar" nos meses seguintes, até ser paga ou excluída. Se você anotou o pagamento como gasto em vez de marcar a conta como paga, exclua a conta a pagar para ela não continuar em "Ainda a pagar".',
    ],
    example: null,
    calculation: null,
    hypotheses: 'Exemplo fictício.',
    facts: [],
    keywords: ['ainda a pagar', 'conta a pagar', 'previsão'],
    related: ['diferenca', 'gasto-fixo', 'marcar-como-paga'],
    sources: [clarevo('D-020', 'D-021')],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: null,
  },
  {
    slug: 'saldo',
    section: 'usar',
    kind: 'tema',
    status: 'publicado',
    title: 'Diferença do mês e saldo da conta',
    subtitle: 'Por que são números diferentes',
    question: 'Por que a diferença do mês não é o saldo da conta?',
    short: 'O saldo depende do que já havia na conta. A diferença do mês olha só para o que entrou e saiu no período.',
    paragraphs: [
      'O saldo da conta depende do quanto havia antes do mês começar, de transferências e de outros movimentos. A diferença do mês olha só para recebimentos e pagamentos do período.',
      'Por isso o Clarevo não chama a diferença do mês de saldo nem de dinheiro disponível. Sem saldo inicial informado, não mostramos um saldo calculado.',
    ],
    example: null,
    calculation: null,
    hypotheses: 'Exemplo fictício.',
    facts: [],
    keywords: ['saldo inicial', 'saldo bancário', 'extrato'],
    related: ['diferenca', 'cheque-especial'],
    sources: [clarevo('D-011')],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: null,
  },
  {
    slug: 'fatura',
    section: 'usar',
    kind: 'tema',
    status: 'publicado',
    title: 'Fatura sem contar duas vezes',
    subtitle: 'Entenda o efeito no seu mês',
    question: 'Anoto as compras do cartão ou o pagamento da fatura?',
    short: 'Anote as compras do cartão ou o pagamento da fatura, nunca os dois: o mesmo consumo contaria duas vezes.',
    paragraphs: [
      'Uma compra de R$ 160 no cartão registra o consumo. Pagar a fatura quita essa obrigação e movimenta a conta. Contar esse pagamento como uma nova compra duplicaria o consumo. Juros e tarifas têm registros próprios.',
      'Cartões ainda não estão disponíveis no Clarevo. Este conteúdo explica o conceito para quando chegarem.',
    ],
    example: null,
    calculation: null,
    hypotheses: 'Exemplo fictício: uma única compra à vista no cartão, sem parcelas, juros ou estornos.',
    facts: [],
    keywords: ['cartão de crédito', 'compra no cartão', 'pagamento da fatura', 'duplicado'],
    related: ['contei-duas-vezes', 'rotativo-cartao'],
    sources: [clarevo('D-020')],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: null,
  },
  {
    slug: 'gasto-fixo',
    section: 'usar',
    kind: 'tema',
    status: 'publicado',
    title: 'Gasto fixo, conta a pagar e gasto anotado',
    subtitle: 'Como cada um entra no mês',
    question: 'Qual a diferença entre gasto fixo, conta a pagar e gasto anotado?',
    short:
      'Um gasto fixo é uma regra que cria a conta a pagar de cada mês. Só quando você marca a conta como paga entra um gasto em Pago, uma única vez.',
    paragraphs: [
      'Um gasto fixo é uma regra: todo mês ele cria uma conta a pagar. Só quando você marca a conta como paga entra um gasto em Pago, uma única vez.',
      'Anotar o mesmo aluguel como gasto e como gasto fixo contaria duas vezes. Parcelas de compras no cartão ficam na fatura.',
    ],
    example: null,
    calculation: null,
    hypotheses: 'Exemplo fictício: aluguel de R$ 2.500,00 com vencimento no dia 5.',
    facts: [],
    keywords: ['aluguel', 'conta mensal', 'repetir todo mês', 'série'],
    related: ['gasto-fixo-variavel', 'estimativa', 'contei-duas-vezes'],
    sources: [clarevo('D-024')],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: null,
  },
  {
    slug: 'estimativa',
    section: 'usar',
    kind: 'tema',
    status: 'publicado',
    title: 'Contas que mudam de valor',
    subtitle: 'Luz, água e gás',
    question: 'O que é um valor estimado?',
    short:
      'Até a conta chegar, o Clarevo usa o valor de referência que você informou, marcado como estimado. Nada é inventado nem alterado sozinho.',
    paragraphs: [
      'Usamos o valor de referência que você informou, marcado como estimado, até você informar o valor de cada conta.',
      'Quando houver contas pagas, mostramos a média das últimas três como sugestão, e você decide se usa.',
    ],
    example:
      'Se as três últimas contas de luz pagas foram de R$ 165,30, R$ 180,00 e R$ 171,90, a média é R$ 172,40. O Clarevo mostra esse valor como sugestão, e você decide se o usa como novo valor de referência.',
    calculation: '(165,30 + 180,00 + 171,90) ÷ 3 = 172,40.',
    hypotheses: 'Contas fictícias de R$ 165,30, R$ 180,00 e R$ 171,90: média de R$ 172,40.',
    facts: [],
    keywords: ['valor estimado', 'valor de referência', 'conta de luz', 'conta de água', 'média'],
    related: ['gasto-fixo', 'marcar-como-paga'],
    sources: [clarevo('D-024')],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: null,
  },
  {
    slug: 'parcelamentos',
    section: 'usar',
    kind: 'tema',
    status: 'publicado',
    title: 'Parcelamentos no Clarevo',
    subtitle: 'Parcela 13 de 48 e o que falta',
    question: 'Como anotar um parcelamento que já começou?',
    short: 'Você informa qual é a próxima parcela; as anteriores ficam como pagas antes do Clarevo. A soma das que faltam não é o valor para quitar.',
    paragraphs: [
      'Ao cadastrar um parcelamento, você informa o total de parcelas e a próxima a pagar. As anteriores aparecem como pagas antes do Clarevo, informadas por você, e não viram gastos.',
      'Cada mês vira uma conta a pagar com o rótulo da parcela, como Parcela 13 de 48. O detalhe mostra quantas faltam, a soma delas e quando vence a última.',
      'Em financiamentos e compras parceladas, a soma das parcelas que faltam inclui juros futuros. Para quitar antes, peça o valor atualizado a quem concedeu o crédito.',
    ],
    example:
      'Financiamento do carro com 48 parcelas de R$ 850,00, 12 pagas antes do Clarevo: faltam 36, que somam R$ 30.600,00, e a última vence em 10/10/2029.',
    calculation: '48 - 12 = 36 parcelas · 36 × 850,00 = 30.600,00 · a 13ª vence em 10/11/2026 e a 48ª, 35 meses depois, em 10/10/2029.',
    hypotheses: 'Exemplo fictício: 48 parcelas iguais de R$ 850,00; a próxima é a 13ª, em 10/11/2026.',
    facts: [],
    keywords: ['parcela', 'financiamento', 'compra parcelada', 'carnê', 'parcelas pagas antes'],
    related: ['quitar-antes', 'amortizacao-price-sac', 'gasto-fixo'],
    sources: [clarevo('D-024')],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: null,
  },
  {
    slug: 'sem-registro',
    section: 'usar',
    kind: 'tema',
    status: 'publicado',
    title: 'Mês sem registro',
    subtitle: 'Por que ele não é um mês sem gastos',
    question: 'Por que um mês aparece com R$ 0,00?',
    short:
      'Um mês sem anotações aparece com R$ 0,00, mas isso não quer dizer que não houve gastos ou recebimentos. Você decide se atualiza; nada é preenchido sozinho.',
    paragraphs: [
      'O Clarevo soma só o que foi anotado. Um mês sem anotações aparece com R$ 0,00, mas isso não quer dizer que não houve gastos ou recebimentos.',
      'Quando você passa um tempo sem anotar, mostramos o que ficou sem registro e você decide se atualiza. Contas de gastos fixos marcadas como pagas entram no mês da data do pagamento, e as parcelas pagas contam no progresso do parcelamento.',
      'Se preferir seguir adiante, o Clarevo não preenche nada por conta própria: os meses continuam marcados como sem registro.',
    ],
    example: null,
    calculation: null,
    hypotheses: 'Exemplo fictício: aluguel de R$ 2.500,00 com vencimento no dia 5 e nenhuma anotação em julho e agosto.',
    facts: [{ text: 'R$ 0,00', source: 0 }],
    keywords: ['mês vazio', 'sem anotação', 'seus últimos meses', 'sem conta registrada'],
    related: ['voltei-depois', 'diferenca'],
    sources: [clarevo('D-030')],
    reviewedOn: REVIEWED_ON,
    reviewEveryMonths: null,
  },
];
